# -*- coding: utf-8 -*-
"""generate_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ME0DIXlp0sxBmDEoATtGKtdt5uN4L_xO
"""

# scripts/generate_data.py

import pandas as pd
import random

years = [2022, 2023, 2024]
quarters = ['Q1', 'Q2', 'Q3', 'Q4']
regions = ['Permian', 'Bakken', 'Eagle Ford', 'Offshore']

data = []

for year in years:
    for quarter in quarters:
        for region in regions:
            # Random production: 4–6 million barrels
            prod = random.randint(4_000_000, 6_000_000)
            # Revenue per barrel: $75–90
            revenue = prod * random.uniform(75, 90)
            # Cost: 45–60% of revenue
            cost = revenue * random.uniform(0.45, 0.60)
            data.append([
                year,
                quarter,
                region,
                prod,
                round(revenue),
                round(cost)
            ])

df = pd.DataFrame(data, columns=[
    'Year', 'Quarter', 'Region', 'Oil_Production_bbl', 'Revenue_USD', 'Cost_USD'
])

df.to_csv('/content/OilProduction.csv', index=False)